global:
  scrape_interval: 15s # Frequenza con cui raccogliere le metriche

scrape_configs:
  - job_name: 'railway-mlops-app'
    static_configs:
      - targets: ['mlopsgrafana-production.up.railway.app:443']
    scheme: https
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
